#!/usr/bin/env python2

# Author Carolyn Begeman
# plot_netCDF_basic
# Created 20180822
# Last modified 20180822
# This function tests the functionality of netCDF4 library with the data generated by PALM

# plottype, plotvar as arguments
# plottype determines whether to read in 2-d or 1-d file
# plottype includes axslice for pertinent figures
# import libraries
import math,os
from netCDF4 import Dataset
import numpy as np
import plot_palm_mod as palm
#import diff_files as diff

filedir5a = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_0deg_slope01_rdf01_deep_long/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'
filedir6a = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_0deg_slope01_rdf01_deep_wide/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'
filedir7a = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_0deg_slope01_rdf01_deep_500sq/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'
filedir8a = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_0deg_slope01_rdf01_koff5/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'
filedir6b = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_0deg_slop01_rdf01_lowresxy/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'
filedir1a = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_batch_022/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'
filedir1b = '/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_batch_023/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/'

run1a = 'res1a'
run1b = 'res1b'
run5a = '0deg,slope01,rdf01,narrow'
run7a = '0deg,slope01,rdf01,wider,koff3'
run8a = '0deg,slope01,rdf01,wider,koff5'
run6a = '0deg,slope01,rdf01,widest'
run6b = '0deg,slope01,rdf01,deep,lowres'

#newrun = [filedir1a,run1a]
newrun = ['/lustre/scratch3/turquoise/cbegeman/palm/jobs/test_ocean_melt_batch_029/RUN_ifort.grizzly_hdf5_mpirun_test_oceanml/','029']
#newrun = [filedir5a,run5a]
cmprun = [filedir6a,run6a]
cmprun2 = [filedir7a,run7a]

plotvar_t = ['umax','vmax','melt','w"u"0','w"v"0','u*','dt','E','E*','ol']
#plotvar = ['Ri','Rf','N2','S2']
plotvar_xz = ['pt','sa','u','v','w']
plotvar_pr = ['pt','sa','prho','rho_ocean','u','v','w','u*2','v*2','w*2','w*u*','w"u"','w*v*','w"v"',
           'e*','e','km','kh','l','wpt','wsa'] 
plotvar2 = ['shf*_xy','sasws*_xy','u*_xy','z0*_xy','z0h*_xy','ol*_xy']

#tplot = [50.*3600.]
#tplot = np.arange(10,210,10)
#tplot = np.multiply(tplot,3600.)
#tplot = np.arange(40,50,1)
#tplot = np.multiply(tplot,3600.)

# standard set of visualizations for new runs

#palm.plot_uv_vector(newrun[0],newrun[1])

#print(palm.cum_melt(filedir1a,tlim=[0.,18.]))
#print(palm.cum_melt(filedir1b,tlim=[0.,18.]))

palm.plot_tseries([newrun[0]],[newrun[1]], plotvar_t)#,tlim=[0.,50.])
#palm.plot_tseries([filedir6b,filedir1a,filedir1b],[run6b,run1a,run1b], plotvar_t,tlim=[0.,50.])
#palm.plot_tseries([newrun[0]],[newrun[1]], plotvar_t)
#palm.plot_tseries([cmprun2[0],filedir8a],[cmprun2[1],run8a], plotvar_t,tlim=[0.,6.])
#palm.plot_tseries([newrun[0],cmprun[0],cmprun2[0]],[newrun[1],cmprun[1],cmprun2[1]], plotvar_t,tlim=[0.,6.])
#palm.plot_tseries([newrun[0],cmprun[0],cmprun2[0]],[newrun[1],cmprun[1],cmprun2[1]], plotvar_t)#,tlim=[0.,1.])
#palm.plot_tseries([filedir5a,filedir6b,filedir6a],[run5a,run6b,run6a], plotvar_t,tlim=[0.,1.])
#palm.plot_tseries([newrun[0],filedir6a],[newrun[1],run6a], plotvar_t,tlim=[0.,1.])

#palm.plot_xz(filedir1a,run1a,plotvar_xz,teval=tplot)
#palm.plot_xz(filedir1b,run1b,plotvar_xz,teval=tplot)
#palm.plot_xz(newrun[0],newrun[1],plotvar_xz)

#palm.plot_pr([filedir1a,filedir1b],[run1a,run1b], plotvar_pr,teval=tplot)
#palm.plot_pr([filedir1b],[run1b], plotvar_pr,teval=tplot)
#palm.plot_pr([filedir1a],[run1a], plotvar_pr,teval=tplot)
#palm.plot_pr([filedir6b,filedir1a,filedir1b],[run6b,run1a,run1b], plotvar_pr,teval=tplot)
palm.plot_pr([newrun[0]],[newrun[1]], plotvar_pr)
#palm.plot_pr([newrun[0],cmprun[0],cmprun2[0]],[newrun[1],cmprun[1],cmprun2[1]], plotvar_pr, teval=tplot)
#palm.plot_pr([newrun[0],cmprun2[0]],[newrun[1],cmprun2[1]], plotvar_pr, teval=tplot)
#palm.plot_pr([newrun[0]],[newrun[1]], plotvar_pr, teval=tplot)
#palm.plot_pr([cmprun[0]],[cmprun[1]], plotvar_pr, teval=tplot)
#palm.plot_pr([cmprun2[0]],[cmprun2[1]], plotvar_pr, teval=tplot)
#palm.plot_pr([newrun[0],filedir6b],[newrun[1],run6b], plotvar_pr, teval=tplot)

#palm.plot_2d_xy(newrun[0],newrun[1],plotvar2)

#palm.plot_tke_budget(newrun[0],newrun[1])
